version: '3.9'

services:
  postgres:
    container_name: postgres
    image: postgres:latest
    ports:
      - '5432:5432'
    environment:
      - PGDATA
      - PGDATABASE
      - PGUSER
      - PGPASSWORD
    volumes:
      - pg_data:/var/lib/postgresql/data
    restart: always

volumes:
  pg_data:
